{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tu.equipo",
    "module": "TemplateFeature",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TemplateFeature-1.0.0.jar",
          "url": "TemplateFeature-1.0.0.jar",
          "size": 2374,
          "sha512": "39576b3011730be65c38efa6609ad2d8c91242714688c6d463adf23ad67ad8f9142ad7d11f1c6da607155ab95b357281e6bdb64be7812429b0491c7be5d366ef",
          "sha256": "e824b75b8ae0852881c0784f2a097099253cc991e175ff1d5c69a1828ab29afb",
          "sha1": "1795341f80b67baa554b1db62fb20605f4aaf62f",
          "md5": "770731bc61f6fbf03e45ae9b831e2fbd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "com.stzteam.forgemini",
          "module": "ForgeMini",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.stzteam.mars",
          "module": "Mars",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "TemplateFeature-1.0.0.jar",
          "url": "TemplateFeature-1.0.0.jar",
          "size": 2374,
          "sha512": "39576b3011730be65c38efa6609ad2d8c91242714688c6d463adf23ad67ad8f9142ad7d11f1c6da607155ab95b357281e6bdb64be7812429b0491c7be5d366ef",
          "sha256": "e824b75b8ae0852881c0784f2a097099253cc991e175ff1d5c69a1828ab29afb",
          "sha1": "1795341f80b67baa554b1db62fb20605f4aaf62f",
          "md5": "770731bc61f6fbf03e45ae9b831e2fbd"
        }
      ]
    }
  ]
}
